### ISSUE TITLE
New weather templates

### ISSUE THREAD

**Issue by FleMo93** [FleMo93/dcs-random-go-weather#2]
Clouds should be randomized. There will be templates for the cloud settings.
### settings.json
```json
"cloudTemplates": [
    "./cloud-templates/Rainy2",
    "./cloud-templates/Clear1"
],
"times": [
   "..."
]
```

### weather-template.json (./cloud-templates/OldWeatherRain.json)
Using the old cloud system the ```preset``` value must set to ```null```
```json
{
    "preset": null,
    "thickness": 0,
    "density": 0,
    "iprecptns": 0,
    "base": {
        "min": 1000,
        "max": 10000
    }
}
```
or using the new weather templates with preset value set to the new template names given by DCS:
```json
{
    "preset": "TemplateRainy2",
    "thickness": 0,
    "density": 0,
    "iprecptns": 0,
    "base": {
        "min": 1000,
        "max": 10000
    }
}
```

* [x] Anpassen der Wolken anhand den JSON Templates
* [ ] weather-templates bereinigen @T3lm3
* [ ] weather-templates ins JSON ändern @FleMo93
* [ ] weather anhand der JSON Templates anpassen

**Comment by T3lm3** [comment]
[NewWeather-Template.zip](https://github.com/FleMo93/dcs-random-go-weather/files/6329171/NewWeather-Template.zip)

All new 30ty Weather Templates, Presets-Name and Cloudsbase min. and max.

**Comment by T3lm3** [comment]
Rename the Packet Folder to "cloud-templates" !

**Comment by T3lm3** [comment]
[DCS-Weatherconfigs.zip](https://github.com/FleMo93/dcs-random-go-weather/files/6329211/DCS-Weatherconfigs.zip)

Repacking Weathersystem.  Rename Folder for Clouds to "cloud-templates" and move in the right Foldersystem.

"clouds-templates" add to settings.json.

Jobs too do! Clearing the "Weather-Templates"
